export default {
	SUCCESS: 200,
	CREATED: 201,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FOBIDDEN: 403,
	NOT_FOUND: 404,
	UNPROCESSABLE_ENTITY: 422,
	INTERNAL_SERVICE_ERROR: 500,
	CLEAR: "clear",
	SHOW_ALERT: "SHOW_ALERT",
	HIDE_ALERT: "HIDE_ALERT",
};
